apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{deployment_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{deployment_name}}
  template:
    metadata:
      labels:
        app: {{deployment_name}}
    spec:
      containers:
        - name: {{deployment_name}}
          image: {{image_uri}}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
